### Task 1:<br>
#### 1.
Write a function to compute 5/0 and use try/except to catch the exceptions.
        

In [ ]:
def divideByZero():
    try:
        a = 5/0
    except ZeroDivisionError:
        print("Divide by Zero Error Occured!")

divideByZero()

#### 2.
Implement a Python program to generate all sentences where subject is in<br>
<b>["Americans","Indians"]</b> and verb is in <b>["Play", "watch"]</b> and the object is in <b>["Baseball","cricket"]</b>.<br><br>
<b>Hint: Subject,Verb and Object should be declared in the program as shown below.</b><br>
subjects=["Americans ","Indians"]<br>
verbs=["play","watch"]<br>
objects=["Baseball","Cricket"]<br><br>
<b>Output should come as below:</b><br>
Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.

In [15]:
def reandomFunc():
    subjects=["Americans","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]
    
    sentenses = [(sub + " " + vb + " " + ob) for sub in subjects for vb in verbs for ob in objects]
    return sentenses
    
lst = reandomFunc()

for i in lst:
    print(i)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task 2:<br>
#### 1.
Write a function so that the columns of the output matrix are powers of the input vector.<br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br><br>
<b>HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.</b>

In [136]:
import numpy as np

def newVander(inp, n, increase):
    arr = np.array(inp)
    
    if(increase == False):
        tmpArr = np.asarray([arr**(n-1-i) for i in range(n)])
    else:
        tmpArr = np.asarray([arr**(n-1-i) for i in range(n,0,-1)])
        
    tmpArr = np.column_stack(tmpArr)
    
    finalArr = np.zeros((len(arr), n),dtype=int)
    
    for i in range(tmpArr.shape[0]):
        for j in range(tmpArr.shape[1]):
            finalArr[i,j] = tmpArr[i,j]
    
    return finalArr
    
    
    
inp=[1,2,3,4,5]
n=4
increase=False

vanArr = newVander(inp,n,increase)
print(vanArr)



    

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
